import { Router } from 'express';
import { authenticate } from '../../middleware/auth';
import { requireSuperAdmin } from '../../middleware/adminAuth';
import usersRoutes from './users.routes';
import organizationsRoutes from './organizations.routes';
import analyticsRoutes from './analytics.routes';
import subscriptionsRoutes from './subscriptions.routes';
import systemRoutes from './system.routes';
import demoRequestsRoutes from './demoRequests.routes';
import contactMessagesRoutes from './contactMessages.routes';
import announcementsRoutes from './announcements.routes';
import auditLogRoutes from './auditLog.routes';
import siteSettingsRoutes from './siteSettings.routes';
import plansRoutes from './plans.routes';
import configRoutes from './config.routes';
import loginActivityRoutes from './loginActivity.routes';
import ipBlockRoutes from './ipBlock.routes';
import sessionsRoutes from './sessions.routes';
import featureFlagRoutes from './featureFlags.routes';
import adminNotificationRoutes from './adminNotifications.routes';
import errorLogRoutes from './errorLogs.routes';
import webhookLogRoutes from './webhookLogs.routes';
import reportsRoutes from './reports.routes';
import emailTemplateRoutes from './emailTemplates.routes';
import filesRoutes from './files.routes';
import bulkEmailRoutes from './bulkEmail.routes';
import securitySettingsRoutes from './securitySettings.routes';
import notificationSettingsRoutes from './notificationSettings.routes';
import landingPageRoutes from './landingPage.routes';
import dlqRoutes from './dlq.routes';
import adminAgentsRoutes from './agents.routes';
import adminConversationsRoutes from './conversations.routes';
import adminLeadsRoutes from './leads.routes';
import adminKnowledgeBasesRoutes from './knowledgeBases.routes';
import adminApiKeysRoutes from './apiKeys.routes';
import adminInvoicesRoutes from './invoices.routes';
import adminWebhooksRoutes from './webhooks.routes';
import ratingsRoutes from './ratings.routes';
import adminMessageTemplatesRoutes from './messageTemplates.routes';
import adminTagsRoutes from './tags.routes';
import messageDeliveryRoutes from './messageDelivery.routes';
import apiUsageRoutes from './apiUsage.routes';
import messageAnalyticsRoutes from './messageAnalytics.routes';
import sentimentAnalysisRoutes from './sentimentAnalysis.routes';
import aiModelsRoutes from './aiModels.routes';
import securityAuditRoutes from './securityAudit.routes';
import conversationQualityRoutes from './conversationQuality.routes';
import leadInsightsRoutes from './leadInsights.routes';
import systemBackupRoutes from './systemBackup.routes';
import tokenUsageRoutes from './tokenUsage.routes';
import faqRoutes from './faq.routes';
import testimonialRoutes from './testimonials.routes';
import legalRoutes from './legal.routes';
import teamPerformanceRoutes from './teamPerformance.routes';

const router: Router = Router();

// All admin routes require authentication + super admin check
router.use(authenticate, requireSuperAdmin);

router.use('/users', usersRoutes);
router.use('/organizations', organizationsRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/subscriptions', subscriptionsRoutes);
router.use('/system', systemRoutes);
router.use('/demo-requests', demoRequestsRoutes);
router.use('/contact-messages', contactMessagesRoutes);
router.use('/announcements', announcementsRoutes);
router.use('/audit-log', auditLogRoutes);
router.use('/site-settings', siteSettingsRoutes);
router.use('/plans', plansRoutes);
router.use('/config', configRoutes);
router.use('/login-activity', loginActivityRoutes);
router.use('/blocked-ips', ipBlockRoutes);
router.use('/sessions', sessionsRoutes);
router.use('/feature-flags', featureFlagRoutes);
router.use('/notifications', adminNotificationRoutes);
router.use('/error-logs', errorLogRoutes);
router.use('/webhook-logs', webhookLogRoutes);
router.use('/reports', reportsRoutes);
router.use('/email-templates', emailTemplateRoutes);
router.use('/files', filesRoutes);
router.use('/bulk-email', bulkEmailRoutes);
router.use('/security-settings', securitySettingsRoutes);
router.use('/notification-settings', notificationSettingsRoutes);
router.use('/landing-page', landingPageRoutes);
router.use('/dlq', dlqRoutes);
router.use('/agents', adminAgentsRoutes);
router.use('/conversations', adminConversationsRoutes);
router.use('/leads', adminLeadsRoutes);
router.use('/knowledge-bases', adminKnowledgeBasesRoutes);
router.use('/api-keys', adminApiKeysRoutes);
router.use('/invoices', adminInvoicesRoutes);
router.use('/webhooks', adminWebhooksRoutes);
router.use('/ratings', ratingsRoutes);
router.use('/message-templates-admin', adminMessageTemplatesRoutes);
router.use('/tags', adminTagsRoutes);
router.use('/message-delivery', messageDeliveryRoutes);
router.use('/api-usage', apiUsageRoutes);
router.use('/message-analytics', messageAnalyticsRoutes);
router.use('/sentiment-analysis', sentimentAnalysisRoutes);
router.use('/ai-models', aiModelsRoutes);
router.use('/security-audit', securityAuditRoutes);
router.use('/conversation-quality', conversationQualityRoutes);
router.use('/lead-insights', leadInsightsRoutes);
router.use('/system-backup', systemBackupRoutes);
router.use('/token-usage', tokenUsageRoutes);
router.use('/faq', faqRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/legal', legalRoutes);
router.use('/team-performance', teamPerformanceRoutes);

export default router;
